# Generated by Django 2.2.24 on 2022-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220519_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='from_evolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon'),
        ),
    ]
