# Generated by Django 2.2.24 on 2022-05-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemon_from_evolve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='from_evolve',
            new_name='from_evolved',
        ),
    ]
